server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
