networks:
  external: true
  name: testtest

services:
  backend:
    image: dogstyle
    networks:
      - testtest
    ports:
      - "8080:8080"
    container_name: compose-bark
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    networks:
      - testtest
    expose:
      - "1433"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Sobaka01234!
    container_name: compose-mssql