FROM openjdk:8-jre-alpine
COPY barkingApp.jar myName.jar
EXPOSE 8080
CMD ["/usr/bin/java", "-jar", "myName.jar"]

#FROM posobachii/bark
#COPY barkingApp.jar test.jar
#COPY sometext.txt sometext.txt

#FROM openjdk:11-jre-slim
#COPY barkingApp.jar myName.jar
#EXPOSE 8080
#CMD ["/usr/local/openjdk-11", "-jar", "myName.jar"]