dog:
  message: El Tuzik

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  profiles:
    active: mssql
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

---
spring:
  profiles: mssql
  datasource:
    url: jdbc:sqlserver://localhost:1450;databaseName=bark_logger
    username: SA
    password: Sobaka01234!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
---
spring:
  profiles: dockerdb
  datasource:
    url: jdbc:sqlserver://192.168.59.108:1433;databaseName=bark_logger
    username: SA
    password: Sobaka01234!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
---