INSERT INTO Users (name, surname, age, email, isAlive)
VALUES ('John', 'Doe', 30, 'john.doe@example.com', true),
       ('Jane', 'Doe', 25, 'jane.doe@example.com', true),
       ('Mark', 'Zuckerberg', 38, 'mark.zuckerberg@meta.com', true),
       ('Elon', 'Musk', 51, 'elon.musk@tesla.com', true),
       ('Jeff', 'Bezos', 58, 'jeff.bezos@amazon.com', true),
       ('Albert', 'Einstein', 143, 'albert.einstein@deceased.com',false),
       ('Marie', 'Curie', 114, 'marie.curie@deceased.com', false),
       ('Leonardo', 'da Vinci', 569, 'leonardo.davinci@deceased.com', false),
       ('William', 'Shakespeare', 469, 'william.shakespeare@deceased.com', false),
       ('Oprah', 'Winfrey', 69, 'oprah.winfrey@own.tv', true),
       ('Stephen', 'Hawking', 76, 'stephen.hawking@deceased.com', false),
       ('Malala', 'Yousafzai', 26, 'malala.yousafzai@gmail.com', true),
       ('Barack', 'Obama', 62, 'barack.obama@whitehouse.gov', true),
       ('Nelson', 'Mandela', 105, 'nelson.mandela@deceased.com', false),
       ('Mahatma', 'Gandhi', 78, 'mahatma.gandhi@deceased.com', false),
       ('Ludwig', 'van Beethoven', 250, 'ludwig.van.beethoven@deceased.com', false),
       ('Vincent', 'van Gogh', 139, 'vincent.van.gogh@deceased.com', false),
       ('Michelangelo', '', 89, 'michelangelo@deceased.com', false),
       ('William', 'Gates', 67, 'william.gates@microsoft.com', true),
       ('Stephen', 'King', 75, 'stephen.king@horror.com', true);
