INSERT INTO item_types (id, type_name, material, description)
VALUES  (1, 'Shirts', 'cotton', 'some sort of description for particular type. probably tags'),
        (2, 'Sweaters', 'cotton', 'some sort of description for particular type. probably tags'),
        (3, 'Pants', 'jeans', 'some sort of description for particular type. probably tags'),
        (4, 'Hats', 'synthetic', 'some sort of description for particular type. probably tags'),
        (5, 'Shoes', 'rubber', 'some sort of description for particular type. probably tags');

INSERT INTO items_all (itemName, itemType_id, qty, price, description)
VALUES  ('Adidas red shirt',1, 5, 1999, 'Random description for shirt type item'),
        ('Adidas blue shirt',1, 5, 1999, 'Random description for shirt type item'),
        ('Nike sports shirt',1, 5, 2499, 'Random description for shirt type item'),
        ('Nike green shirt',1, 5, 2499, 'Random description for shirt type item'),
        ('Daewoo super shirt',1, 5, 3999, 'Random description for shirt type item'),
        ('Uber T-shirt',1, 5, 3399, 'Random description for shirt type item'),
        ('Uber T-shirt',1, 5, 3399, 'Random description for shirt type item'),
        ('Uber T-shirt',1, 5, 3399, 'Random description for shirt type item'),

        ('Adidas black hoodie',2, 5, 6999, 'Random description for sweater type item'),
        ('Adidas white hoodie',2, 5, 5999, 'Random description for sweater type item'),
        ('Puma hoodie no-sleeves',2, 5, 5999, 'Random description for sweater type item'),
        ('Nike black hoodie',2, 5, 5999, 'Random description for sweater type item'),
        ('Nike white hoodie',2, 5, 5999, 'Random description for sweater type item'),
        ('Daewoo techinal hoodie',2, 5, 5999, 'Random description for sweater type item'),
        ('Daewoo techinal hoodie',2, 5, 5999, 'Random description for sweater type item'),
        ('Daewoo techinal hoodie',2, 5, 5999, 'Random description for sweater type item'),

        ('Blue jeans',3, 5, 2999, 'Random description for pants type item'),
        ('Black jeans',3, 5, 3499, 'Random description for pants type item'),
        ('White jeans',3, 5, 1799, 'Random description for pants type item'),
        ('Cotton white pants',3, 5, 2399, 'Random description for pants type item'),
        ('Sport pants',3, 5, 3499, 'Random description for pants type item'),
        ('Cotton black pants',3, 5, 2899, 'Random description for pants type item'),
        ('Cotton black pants',3, 5, 2899, 'Random description for pants type item'),
        ('Cotton black pants',3, 5, 2899, 'Random description for pants type item'),

        ('Akubra',4, 5, 1299, 'Random description for hats items'),
        ('Baseball cap',4, 5, 699, 'Random description for hats items'),
        ('Bucker hat',4, 5, 1499, 'Random description for hats items'),
        ('Gatsby',4, 5, 899, 'Random description for hats items'),
        ('Kalpak',4, 5, 799, 'Random description for hats items'),
        ('Sun hat',4, 5, 1099, 'Random description for hats items'),
        ('Sun hat',4, 5, 1099, 'Random description for hats items'),
        ('Sun hat',4, 5, 1099, 'Random description for hats items'),

        ('Trainers',5, 5, 3499, 'Random description for shoes'),
        ('Uggs',5, 5, 2999, 'Random description for shoes'),
        ('Work boots',5, 5, 4999, 'Random description for shoes'),
        ('Army boots',5, 5, 4599, 'Random description for shoes'),
        ('Platform pumps',5, 5, 2999, 'Random description for shoes'),
        ('High heels',5, 5, 3399, 'Random description for shoes'),
        ('Trainers',5, 5, 3499, 'Random description for shoes'),
        ('Uggs',5, 5, 2999, 'Random description for shoes'),
        ('Work boots',5, 5, 4999, 'Random description for shoes'),
        ('Army boots',5, 5, 4599, 'Random description for shoes'),
        ('Platform pumps',5, 5, 2999, 'Random description for shoes'),
        ('High heels',5, 5, 3399, 'Random description for shoes'),
        ('Trainers',5, 5, 3499, 'Random description for shoes'),
        ('Uggs',5, 5, 2999, 'Random description for shoes'),
        ('Work boots',5, 5, 4999, 'Random description for shoes'),
        ('Army boots',5, 5, 4599, 'Random description for shoes'),
        ('Platform pumps',5, 5, 2999, 'Random description for shoes'),
        ('High heels',5, 5, 3399, 'Random description for shoes'),
        ('Trainers',5, 5, 3499, 'Random description for shoes'),
        ('Uggs',5, 5, 2999, 'Random description for shoes'),
        ('Work boots',5, 5, 4999, 'Random description for shoes'),
        ('Army boots',5, 5, 4599, 'Random description for shoes'),
        ('Platform pumps',5, 5, 2999, 'Random description for shoes'),
        ('High heels',5, 5, 3399, 'Random description for shoes'),
        ('Trainers',5, 5, 3499, 'Random description for shoes'),
        ('Uggs',5, 5, 2999, 'Random description for shoes'),
        ('Work boots',5, 5, 4999, 'Random description for shoes'),
        ('Army boots',5, 5, 4599, 'Random description for shoes'),
        ('Platform pumps',5, 5, 2999, 'Random description for shoes'),
        ('High heels',5, 5, 3399, 'Random description for shoes'),
        ('Trainers',5, 5, 3499, 'Random description for shoes'),
        ('Uggs',5, 5, 2999, 'Random description for shoes'),
        ('Work boots',5, 5, 4999, 'Random description for shoes'),
        ('Army boots',5, 5, 4599, 'Random description for shoes'),
        ('Platform pumps',5, 5, 2999, 'Random description for shoes'),
        ('High heels',5, 5, 3399, 'Random description for shoes'),
        ('Trainers',5, 5, 3499, 'Random description for shoes'),
        ('Uggs',5, 5, 2999, 'Random description for shoes'),
        ('Work boots',5, 5, 4999, 'Random description for shoes'),
        ('Army boots',5, 5, 4599, 'Random description for shoes'),
        ('Platform pumps',5, 5, 2999, 'Random description for shoes'),
        ('High heels',5, 5, 3399, 'Random description for shoes');

INSERT INTO items_all (itemName, itemType_id, qty, price, description, is_favorite)
VALUES  ('Favorite T-Shirt',1, 5, 1999, 'Random description for shirt type item',1),
        ('Favorite Sweater',2, 5, 1999, 'Random description for sweater type item',1),
        ('Favorite pants',3, 5, 2499, 'Random description for pants type item',1),
        ('Favorite hat',4, 5, 2499, 'Random description for hats items',1),
        ('Favorite shoes',5, 5, 3999, 'Random description for shoes',1),
        ('Another favorite T-Shirt',1, 5, 3399, 'Random description for shirt type item', 1);




