create table db_customers
(
    id       bigint generated by default as identity,
    name     varchar(255),
    surname  varchar(255),
    country  varchar(255),
    email    varchar(255),
    password varchar(255),
    primary key (id)
);


create table db_cards
(
    id          bigint generated by default as identity,
    amount      integer not null,
    currency    varchar(255),
    exp_date    varchar(255),
    customer_id bigint,
    primary key (id)
);

